tranquilitybase-io/tb-gcp

tb-gcp-deploy/pack/init.sh

This reduces the dependency on Internet access during the Landing Zone's
deployment.

Run terraform init on img creation

---

tb-gcp-tr/itop/helm/itop/templates/gateway.yaml

```
* module.itop.helm_release.itop: 1 error(s) occurred:
* helm_release.itop: rpc error: code = Unknown desc = validation failed: unable to recognize "": no matches for kind "Gateway" in version ""
```

Removes license banner to avoid error

---

tb-gcp-tr/bootstrap/variables.tf

Example error:
```
module.UI-static-host.null_resource.upload_to_static_host: Still creating... (10s elapsed)
module.UI-static-host.null_resource.upload_to_static_host (local-exec): Traceback (most recent call last):
module.UI-static-host.null_resource.upload_to_static_host (local-exec):   File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil", line 21, in <module>
module.UI-static-host.null_resource.upload_to_static_host (local-exec):     gsutil.RunMain()
module.UI-static-host.null_resource.upload_to_static_host (local-exec):   File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil.py", line 124, in RunMain
module.UI-static-host.null_resource.upload_to_static_host (local-exec):     sys.exit(gslib.__main__.main())
module.UI-static-host.null_resource.upload_to_static_host (local-exec): …
```

Avoids terraform-server running out of memory

---

tb-gcp-tr/landingZone/variables.tf

Moved default directory of UI endpoint-meta.json to /opt/ directory so that the file persists during retries and is committed into source repos

API Endpoint address persistence

---

tb-gcp-tr/itop/helm/itop/templates/istio-serviceentry.yaml
tb-gcp-tr/landingZone/input.tfvars

6d0f903 (Ricardo Cordeiro, 21 minutes ago)
Unpins GKE version 1.12.8; latest is now supported
With the istio fix deployed on the previous commit, the version pinning is
no longer required. Also, GKE masters with the pinned version are no longer
available as shown in the following recent error:
```
A 2019-10-01T10:27:58.790002617Z *
module.gke-ssp.google_container_cluster.gke: 1 error(s) occurred: A
2019-10-01T10:27:58.790006132Z * google_container_cluster.gke: googleapi:
Error 400: No valid versions with the prefix "1.12.8" found., badRequest
```
95edaea (Ricardo Cordeiro, 23 minutes ago)
Removes unneeded Cloud SQL Proxy istio ServiceEntry
This solves the following error seen on GKE clusters post version 1.12.8:
``` 
Error: Error applying plan:
1 error(s) occurred:
* …
```

Unpins GKE version & fixes incompatibility w/ istio

---

tb-gcp-tr/bootstrap/datasources.tf
tb-gcp-tr/bootstrap/main.tf
tb-gcp-tr/bootstrap/network.tf
tb-gcp-tr/bootstrap/variables.tf
tb-gcp-tr/bootstrap/versions.tf

This requires the use of terraform 0.12 for bootstrap deployments from
now on.

Transitions bootstrap deployment to terraform 0.12

---

tb-gcp-activator/files/jenkins-deployment.yaml
tb-gcp-activator/main.tf
tb-gcp-activator/variables.tf
tb-gcp-tr/landingZone/deployment.yaml
tb-ssp-gcp/Dockerfile
tb-ssp-gcp/README.md
tb-ssp-gcp/modules/subnet_pool_handler.py
tb-ssp-gcp/tf_create_subnets/main.tf

This PR contains the following changes:
1. Updated the dockerfile to make sure the activator is running the latest terraform version and removed stale repo references. 
2. Changed the google provider version to `2.5` in the activator.
3. Corrected the terraform syntax in some places.

Issue #113: Updated the docker image to make the Jenkins LB private

---

tb-gcp-tr/apis-activation/main.tf
tb-marketplace/tb-dep-manager/tranquility-base.jinja

Enabled IAM recommender.googleapis.com for all Shared services projects and disabled also non-used APIs. Closes #169
Evidence:
_root@tb25ed0c-bootstrap-vm:/opt/tb/repo/tb-gcp-tr/landingZone# ./tb-welcome
Time start: 2020-03-20 11:44:46
....
Apply complete! Resources: 2 added, 4 changed, 0 destroyed.
Outputs:
nat-static-ip = 35.246.101.62
sec-cluster_master_auth_0_client_key = 
sec-gke-endpoint = 35.246.101.151
vault-root-token = s.1547G8NbEgZo0dsAYQxXyuJg
.....
Time end: 2020-03-20 12:09:52
root@tb25ed0c-bootstrap-vm:/opt/tb/repo/tb-gcp-tr/landingZone#_

Enabled IAM recommender.googleapis.com

---

tb-gcp-tr/landingZone/no-itop/main.tf
tb-gcp-tr/landingZone/with-itop/main.tf
tb-marketplace/tb-config-creator/README.md
tb-marketplace/tb-config-creator/tb-config-creator

Decommission the SSP deployment in appengine and removed appengine.googleapis.com from bootstrap enabling
Closes #182 , #192

Decommission SSP appengine deployment and disabling of appengine.googleapis.com from bootstrap

---

tb-test/cloudbuild.yaml
tb-test/cloudbuild_master_release.yaml

- reverted cloudbuild.yaml to be used for pushes to github repo.
- tb-test/cloudbuild_master_release.yaml  is to be used for when master is tagged. Will set up a cloud build trigger to use this yaml specifically.

Cloudbuild patch 1

---

tb-gcp-tr/bootstrap/main.tf

Added monitoring API to list of services created in bootstrap project, as it is a hidden dependency of the container API and enabled even if not explicitly declared. The current code works, but if monitoring api is not explicitly declared and the TF plan / apply needs to be rerun for any reason, it exhibits strange behavior of removing the monitoring api, which then also implicitly disables the container API.

added monitoring api

---

tb-gcp-tr/apis-activation/main.tf

API is meant to be enabled on the host project, not the service projects.

Fixing DNS api enabling

---

tb-marketplace/tb-config-creator/tb-config-creator

*What kind of change does this PR introduce?*
Fixes a typo on a help message output.
Fixes `tb-marketplace/tb-config-creator/tb-config-creator`'s script's usage output from:
```
./tb-config-creator -0 123953123545 -b F9C122-73127B-50AE5B
```
to the correct form:
```
./tb-config-creator -o 123953123545 -b F9C122-73127B-50AE5B
```
- **RDHA-GFT** please review this part.  
- **scottholmangft** please review this part.  
This fix has been tested during the deployment into a customer environment.

Fixes #365 tb-config-creator help typo fix

---

tb-gcp-tr/shared-vpc/main.tf

*What kind of change does this PR introduce?*
Stops the `shared-vpc` terraform module from ignoring the `bastion_subnet_cidr` variable.
Allow for the `bastion-subnetwork` primary CIDR range to be changed before deployment.
A more thorough discussion on this has been provided on issue #364's opening comment.
- **RDHA-GFT** please review this part.  
- *scottholmangft** please review this part.  
This fix has been successfully tested while deploying a customer environment.

Fixes #364 bastion CIDR variable is no longer ignored

---

tb-gcp-deploy/pack/packer-no-itop.json
tb-gcp-tr/landingZone/no-itop/input.tfvars
tb-gcp-tr/landingZone/no-itop/main.tf
tb-gcp-tr/landingZone/no-itop/variables.tf
tb-gcp-tr/shared-dac/jenkins-master.yaml
tb-gcp-tr/shared-dac/namespaces.yaml

deploys jenkins onto the shared gke cluster on a separate namespace called cicd
Also made provision to create namespaces controlled by a separate yaml file source from the shared-dac folder in tb-gcp-tr
- [*] Feature  
This is as part of the Activator Deploy milestone
@rjmco , @scottholmangft , @wills-gft , @afamgft 
- [*] This PR is linked to one or more issues.  #279 
[adct@tb-kube-proxy-3wn5 ~]$ kubectl get namespaces
NAME              STATUS   AGE
cicd              Active   99m
default           Active   109m
istio-operator    Active   103m
istio-system      Active   102m
kube-node-lease   Active   109m
kube-public       Active   109m
kube-system       Active   109m
ssp               Active …

Issue 279a - Deploy Jenkins onto the shared gke cluster as part of the landingzone

---

tb-gcp-tr/shared-vpc/main.tf

Useful if Cloud NAT is removed on fully private environments which is useful if Cloud NAT is removed on fully private environments.
The purpose has been fully described on issue #363. Here's a small quote of the whole issue which summarizes the purpose:
> Even though Cloud NAT is deployed by default and it implicitly enables Private Google Access (PGA), this functionality should be enabled explicitly for the shared-network-snet subnetwork deployed by the shared-vpc module.
further arguments are presented on the issue #363. 
- **RDHA-GFT** please review this part.  
- **scottholmangft** please review this part.  
This commit was successfully deployed on a customer environment.

Fixes #363 Enables PGA on shared-network-snet

---

tb-gcp-tr/kubernetes-cluster-creation/variables.tf

Changed the node machine type and boot disk size to match the resource that is required to run the SSP and Jenkins master changed from n1-standard-2 to n1-standard-4 and the boot disk size from 10G to 30G the cost is double of what is present at the moment from 0.64 hourly per node to 0.134 hourly per node but with the present setup we anyway had the nodes autoscaled to 5-6 nodes because of the initial load.
Changed the machine type and boot disk size in the kubernetes-cluster-creation module/variables.tf file
- [*] Bugfix  
- **Review B** please review …

changed the node machine type and boot disk size

---

tb-marketplace/tb-config-creator/tb-config-creator

- Fixes #443 Enables deploymentmanager API to avoid asking user
Please check the boxes that applies to this PR.
This PR fixes issue #443 by enabling the deploymentmanager.googleapis.com API on the bootstrap project prior to avoid the user being asked to enabled during GCDM deployment.
- Anyone
Test results:
```
$ gcloud deployment-manager deployments create issue-443 --config tb-marketplace/tb-dep-manager/test_config.yaml
The fingerprint of the deployment is b'noMTphdga1uyymZvXNPRfA=='
Waiting for create [operation-1597781790727-5ad2c90109d35-67ef3775-f265abc7]...done.
Create operation operation-1597781790727-5ad2c90109d35-67ef3775-f265abc7 completed successfully.
NAME                                     TYPE …
```

Fixes #443 Enables deploymentmanager API to avoid asking user

---

tb-marketplace/tb-config-creator/tb-config-creator

Removed the default firewall rule deletion commands from tb-config-creator, which will be replaced with org policy skip default network creation rule. 
Needs to be merged at the same time as the policy is enabled to avoid disrupting deployments.

removed default net creation

---

tb-gcp-tr/landingZone/no-itop/main.tf
tb-gcp-tr/shared-bastion/main.tf
tb-gcp-tr/shared-bastion/variables.tf
tb-gcp-tr/shared-vpc/main.tf

Changes the Shared VPC default firewall rules to the following three:
Name: allow-bastion-ingress
Direction: INGRESS
Source: any GCE instance running with the bastion-service-account service account
Destination ports: all TCP ports on all GCE instances
Name: allow-iap-ingress
Direction: INGRESS
Destination ports: all TCP ports on all GCE instances
Source: 35.235.240.0/20 (these are the known Identity-Aware Proxy ranges)
Name: allow-proxy-http-ingress
Direction: INGRESS
Destination ports: TCP ports 80, 443, 8008, 8080 and 8443 on all GCE instances
Source: any GCE instance running with the proxy-sa service account
Remove test firewall rules and other unneeded sources such as the NAT Gateway's IP.

Fixes #503 consolidate bastion & proxy FW rules

---

tb-gcp-tr/shared-bastion/main.tf

... applies the same fix as 36a363d to the squid_proxy_template as well
Fixes #504 once again as one of the instance templates was missed on my 1st attempt at this (#507). Hopefully this is the last that we will see of the error logged on the issue.

Refixes #504: one instance template was missed

---

tb-gcp-tr/landingZone/no-itop/main.tf

by bumping terraform-google-cloud-storage to the logging-v3 head
As described on #527, this PR fixes the following deprecation warning:
> ```
> Step #0 - "Package image":     googlecompute: Warning: Attribute is deprecated
> Step #0 - "Package image":     googlecompute:
> Step #0 - "Package image":     googlecompute:   on .terraform/modules/gcs_bucket_logging/modules/simple_bucket/main.tf line 22, in resource "google_storage_bucket" "bucket":
> Step #0 - "Package image":     googlecompute:   22:   bucket_policy_only = var.bucket_policy_only
> Step #0 - "Package image":     googlecompute: 
> Step #0 - "Package image":     googlecompute: Please use the uniform_bucket_level_access as this field …
```

Solves #527 bucket_policy_only deprecation warning

---

tb-gcp-deploy/pack/packer-no-itop.json
tb-gcp-tr/dns-instances/main.tf
tb-gcp-tr/dns-instances/variables.tf
tb-gcp-tr/landingZone/no-itop/main.tf
tb-gcp-tr/shared-bastion/data_sources.tf
tb-gcp-tr/shared-bastion/main.tf
tb-gcp-tr/shared-bastion/outputs.tf
tb-gcp-tr/shared-vpc/outputs.tf

Adds DNS A records for the instances in the shared-bastion project. These A records are added to the "private-shared" DNS zone.
https://github.com/tranquilitybase-io/tb-gcp/issues/321
Allow for a known DNS zone to be used for all records rather than relying on google cloud's internal DNS.

Fixes Issue-321 (#531) Add A record to Cloud DNS for all compute instances

---

tb-gcp-tr/shared-dac/eagle_console.yaml

Changes the Jenkins URL used by GCP DAC from jenkins-master-svc.cicd to eagle-console.tranquilitybase-demo.io/jenkins-service

Replace jenkins URL environment variable

---

tb-gcp-tr/dac-secret/main.tf
tb-gcp-tr/dac-secret/variables.tf
tb-gcp-tr/landingZone/no-itop/main.tf
tb-gcp-tr/shared-dac/eagle_console.yaml
tb-gcp-tr/shared-dac/jenkins-master.yaml

This PR creates 2 secrets within the EC cluster:
dac-user-pass in the ssp namespace.
dac-user-pass in the cicd namespace.
This secret contains the credentials for the DAC user. The password for this user is generated randomly on every deployment using the random password terraform resource.
These secrets are then integrated into the kubernetes manifest files with the jenkins and dac container's pulling the values from these secrets and storing it as environment variables.
Please check the boxes that applies to this PR.
To allow the 'dac user' (not an admin) to Jenkins so that DAC can monitor running jobs on Jenkins.
To also prevent the need for hardcoding the Dac user credentials in various places.

Issue 508 - Add 'dac user' to Jenkins so that DAC can monitor running jobs on Jenkins 

---

tb-gcp-tr/kubernetes-cluster-creation/variables.tf
tb-gcp-tr/landingZone/no-itop/main.tf
tb-gcp-tr/landingZone/no-itop/variables.tf

Provides the node pools in the k8 cluster with full access to all Google Cloud Services as recommended per Google's best practises. 
https://github.com/tranquilitybase-io/tb-gcp/issues/552

Issue 552 - Provide the node pools with full access scope for all Google Cloud Services as per best practises

---

tb-gcp-tools/tb-auto-projects-deleter/cloud-function/main.py
tb-gcp-tr/kubernetes-cluster-creation/variables.tf

Changes the default machine image type for the GKE cluster from n1-standard-4 to e2-standard-4 to avoid STOCKOUT error when deploying in the EU a/b zones under the demo org.
- **Review B** please review this part.  
- [ x] This PR is linked to one or more issues.  
- [ x] This PR has been tested (attach evidence if possible).  
-

Issue 589 - Changed default machine image type for GKE

---

tb-gcp-tr/shared-dac/jenkins-master.yaml

Rolling back jenkins version after A/B testing in lower environments 
Jenkins 0.0.19 has breaking changes preventing activator deployment

#656 rolled back jenkins from v0.0.19 to 0.0.14
