tb-gcp-tr/bootstrap/files/bootstrap.sh
By default the Landing Zone deployment will be re-tried 10 times with a
1 minute pause between tries. This works around potential GCP instabilty
which may be occuring during deployment.
=> Retries the Landing Zone TF deployment

tb-gcp-tr/landingZone/outputs.tf
=> updated output file to surface vault root token

tb-gcp-tools/tb_projects_deleter/README.md, tb-gcp-tools/tb_projects_deleter/tb_projects_deleter
This tools aims to speed up the development process of the bootstrap and
landing zone by automating the tasks of deleting the associated projects
and folders.
=> Adds tb_projects_deleter helper tool

tb-gcp-activator/files/jenkins-deployment.yaml, tb-gcp-tr/gae-self-service-portal/main.tf, tb-gcp-tr/gae-self-service-portal/outputs.tf, tb-gcp-tr/gae-self-service-portal/variables.tf, tb-gcp-tr/landingZone/deployment.yaml, tb-gcp-tr/landingZone/outputs.tf, tb-gcp-tr/vault/k8s/vault.yaml
This change has been tested in the GCP environment.
=> Made the bucket private and removed the load balancer

README.md
Update README.md with reference to issues list
Corrected the .me to .md
=> Update README.md with reference to issues list

tb-gcp-activator/files/jenkins-deployment.yaml, tb-gcp-tr/bootstrap/main.tf, tb-gcp-tr/folder-structure-creation/examples/advanced/providers.tf, tb-gcp-tr/folder-structure-creation/examples/simple/providers.tf, tb-gcp-tr/itop/examples/simple/provider.tf, tb-gcp-tr/kubernetes-cluster-creation/iam.tf, tb-gcp-tr/landingZone/deployment.yaml, tb-gcp-tr/landingZone/main.tf, tb-gcp-tr/shared-vpc/examples/advanced/providers.tf, tb-gcp-tr/shared-vpc/examples/simple/providers.tf, tb-gcp-tr/single-bastion/providers.tf, tb-gcp-tr/vault/k8s/vault.yaml
This PR includes the following changes:
1. Updated the google provider version to 2.5 because the latest version is not working
2. Reverted the load balancers to public
=> Updated the google provider version

tb-gcp-tools/tb-projects-deleter/tb-projects-deleter, tb-marketplace/tb-gcp-dep-guide.md
=> Clean-up service accounts

tb-marketplace/tb-dep-manager/tranquility-base.jinja.display
Updates required to match Marketplace requirements
=> Updates required to match Marketplace requirements

tb-gcp-tools/tb-projects-deleter/README.md, tb-gcp-tools/tb-projects-deleter/tb-projects-deleter
Remove IAM policy bindings for folder and for Billing account
Closes #132
=> Remove IAM policy bindings for folder and for Billing account

tb-gcp-tools/tb-projects-deleter/README.md, tb-gcp-tr/folder-structure-creation/examples/advanced/terraform.tfvars, tb-gcp-tr/landingZone/no-itop/input.tfvars, tb-gcp-tr/landingZone/no-itop/main.tf, tb-gcp-tr/landingZone/no-itop/outputs.tf, tb-gcp-tr/landingZone/no-itop/variables.tf, tb-gcp-tr/landingZone/with-itop/input.tfvars, tb-gcp-tr/landingZone/with-itop/main.tf, tb-gcp-tr/landingZone/with-itop/outputs.tf, tb-gcp-tr/landingZone/with-itop/variables.tf, tb-gcp-tr/shared-projects-creation/main.tf, tb-gcp-tr/shared-projects-creation/outputs.tf, tb-gcp-tr/shared-projects-creation/variables.tf, tb-gcp-tr/shared-vpc/examples/advanced/terraform.tfvars, tb-gcp-tr/shared-vpc/examples/simple/terraform.tfvars
=> Changed  name of "security" landing zone "secrets"

tb-marketplace/tb-config-creator/tb-config-creator
Check output of "folder describe" command rather than "folder list"
Fixes #189
=> Replaced gcloud command list by describe to fix issue

tb-gcp-tools/tb-projects-deleter/tb-projects-deleter
=> Issue #196 - Remove project binding off billing account at deletion

tb-gcp-tools/tb-projects-deleter/tb-projects-deleter
Removes TB  repo at project deletion
Closes #199
=> Removes TB repo at project deletion

tb-marketplace/tb-config-creator/tb-config-creator
Delete default VPC
Closes #194
=> Delete default VPC

tb-gcp-tools/tb-projects-deleter/tb-projects-deleter
Project billing bindings removed for shared services projects
Closes: #196
=> Remove shared services projects billing bindings

tb-gcp-deploy/pack/packer-no-itop.json, tb-gcp-tools/tb-projects-deleter/README.md, tb-gcp-tr/landingZone/no-itop/input.tfvars, tb-gcp-tr/landingZone/no-itop/main.tf, tb-gcp-tr/landingZone/no-itop/variables.tf, tb-gcp-tr/landingZone/with-itop/input.tfvars, tb-gcp-tr/landingZone/with-itop/main.tf, tb-gcp-tr/landingZone/with-itop/variables.tf, tb-gcp-tr/shared-bastion/main.tf, tb-gcp-tr/shared-bastion/variables.tf, tb-gcp-tr/shared-projects-creation/main.tf, tb-gcp-tr/shared-projects-creation/outputs.tf, tb-gcp-tr/shared-projects-creation/variables.tf, tb-gcp-tr/shared-vpc/main.tf, tb-gcp-tr/shared-vpc/outputs.tf
Renamed tb-bastion to share-bastion
Closes #195
=> Renamed tb-bastion to share-bastion

tb-test/cloudbuild.yaml
=> Update cloudbuild to add tags

tb-gcp-tr/landingZone/no-itop/main.tf, tb-gcp-tr/vault/k8s/vault.yaml
Created a new namespace "vault" and deployed Vault into that namespace.
=> issue-96: Changed namespace for vault.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/standard_issue.md
Initial proposal for issue templates
=> Create issue templates

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Closes #273. My next PR will be a lot better :)
=> PR request template

tb-gcp-tr/shared-bastion/main.tf
=> Fixing image pointer

tb-gcp-tr/apis-activation/main.tf, tb-gcp-tr/landingZone/no-itop/input.tfvars, tb-gcp-tr/landingZone/no-itop/main.tf, tb-gcp-tr/landingZone/no-itop/variables.tf, tb-gcp-tr/shared-vpc/main.tf, tb-gcp-tr/shared-vpc/variables.tf, tb-marketplace/tb-config-creator/tb-config-creator
closes  #52    
Had to open a new PR.
Purpose
Added private DNS zone for the shared VPC, so services can be contacted via a domain e.g eagle-console.private.landingzone.com.
Added an optional argument to the config script for labelling the bootstrap project with an admin label (something we should be using for development at least).
=> Issue 52 updated

tb-gcp-tr/apis-activation/main.tf
Enables 2 APIs for the shared bastion project
- [*] Bugfix  
To enable the tb-kube-proxy host to access the shared gke cluster and use kubectl against them
=> Changed the api for the bastion project to include K8 and services

tb-gcp-tr/landingZone/eagle_console.yaml, tb-gcp-tr/landingZone/no-itop/ec-configuration-file.tf
adds the DAC services to the shared gke cluster and also contains all the patching that was done to get it working as one stack from the demo yesterday
- [*] Bugfix  
- [*] Feature  
This adds a new feature DAC to the SSP 
@sunderhill-gft , @Salles-FA 
- [*] This PR has been tested (attach evidence if possible).  
These changes were tested as part of the demo
=> Issue 255a DAC code added to the eagle_console yaml

tb-gcp-tr/landingZone/eagle_console.yaml
What kind of change does this PR introduce?
update to use the newer tb-db image, instead of tb-houston-service-mysql57 image. Due to db moving to a new repo.
=> use tb-db image in eagle_console.yaml

tb-gcp-tr/landingZone/istio-kiali_new.yaml, tb-gcp-tr/landingZone/istio-services_new.sh, tb-gcp-tr/landingZone/tb-welcome
Created Gateway, VS and destination rule to access Kiali via a private IP/kiali 
- [x ] Feature  
Kiali needs to be accessible via IP
-Arvind
-Caron
- [ x] This PR has been tested (attach evidence if possible).
=> kiali dashboard access

tb-gcp-tr/landingZone/eagle_console.yaml, tb-gcp-tr/landingZone/no-itop/main.tf, tb-gcp-tr/shared-dac/jenkins-master.yaml
1.) Jenkins deployment modified to take care of the secret that gets created during the landingzone deployment
2.) DAC deployment yaml modified to include the Jenkins base url 
3.) Houston service deployment modified to include client id for google login
- [*] Feature  
#394 
- @sunderhill-gft @karwootang-gft  please review eagle_console.yaml file
-  @wills-gft  please review Jenkins and the main.tf part in the landingzone.  
- [*] This PR is linked to one or more issues.  
The DAC can kick off a deploy and Jenkins builds into gcp automatically …
=> Issue-394a Service account for Jenkins

tb-gcp-tr/landingZone/istio-grafana_new.yaml, tb-gcp-tr/landingZone/istio-services_new.sh
Grafana and Kiali integrated in one sh script in the LZ. 
- [x ] Feature  
**During testing,  the LZ deployed successfully**
**Gateways, VS, and DR created successfully on LZ deployment**
**Kiali is accessible on the LZ deployment**
**Grafana is also now  accessible on the LZ deployment**
Caron
Arvind
=> Grafana & Kiali Access

tb-gcp-tr/landingZone/istio-default-install.sh
Pinned istio to 1.6.8 to prevent 1.7 being pulled down and installed which is not compatible with current deployment code.
- **Review B** please review this part.  
- [ X] This PR has passed style guidelines.
=> Issue istio version fix

tb-marketplace/tb-config-creator/tb-config-creator, tb-marketplace/tb-dep-manager/test_config.yaml, tb-marketplace/tb-dep-manager/tranquility-base.jinja.schema
Changes created-by to created_by in the schema file for deploy manager. Was causing a intermittent bug with deploy manager.
=> created-by schema fix

tb-gcp-tr/shared-dac/eagle_console.yaml
Add persistent storage for mysql and redis
=> Add persistent storage for mysql and redis

tb-gcp-tr/shared-dac/eagle_console.yaml, tb-gcp-tr/shared-dac/jenkins-master.yaml
Redacts some fields that were misplaced and unnecessary and fixes issues that were showing up in a linter.
(read above)
=> [Refactor] Fixes shared-dac rogue code & syntax

tb-gcp-tools/tb-projects-deleter/tb-projects-deleter, tb-marketplace/tb-config-creator/tb-config-creator
Prevents changing billing account IAM policy in parallel from occasionally failing. 
Fixes #510 (see above)
=> Fixes #510: prevents billing account IAM change fail

tb-gcp-tr/landingZone/no-itop/main.tf, tb-gcp-tr/landingZone/no-itop/variables.tf, tb-gcp-tr/shared-bastion/main.tf, tb-gcp-tr/shared-bastion/variables.tf, tb-gcp-tr/shared-vpc/main.tf, tb-gcp-tr/shared-vpc/outputs.tf, tb-gcp-tr/shared-vpc/variables.tf
Solves #518 allows bastion subnet name change
(as set on the right-pane)
=> Solves #518 allows bastion subnet name change

tb-gcp-tr/landingZone/no-itop/main.tf, tb-gcp-tr/landingZone/no-itop/variables.tf, tb-gcp-tr/shared-projects-creation/main.tf, tb-gcp-tr/shared-projects-creation/variables.tf
Solves both:
- #521: Allow deployment of custom IAM bindings on `shared-network-<random>`; and
- #522: Allow deployment of custom IAM bindings on `shared-network-<random>`. 
Tested with both default values (empty lists) and custom values.
=> Solves #521 & #522: Deploy IAM on net & billing projects

tb-gcp-tr/landingZone/no-itop/main.tf, tb-gcp-tr/landingZone/no-itop/variables.tf, tb-gcp-tr/shared-dac/eagle_console.yaml, tb-gcp-tr/shared-dac/jenkins-master.yaml, tb-gcp-tr/shared-dac/storageclasses.yaml
PVC's and SC's for jenkins, and the ec (redis and mysql). I tried consolidating both mysql and redis into one SC, but this can only be done when the SC is set to default... Other than that I got this error attached and also pods go on pending state when I consolidated the two sc's into one 
- [ x] Feature  
@rjmco
=> Fixes #493: Retains MySQL, Redis & Jenkins PVs

tb-gcp-tr/landingZone/create-private-ingress-gateway.sh, tb-gcp-tr/landingZone/no-itop/variables.tf, tb-gcp-tr/tls/variables.tf
changed dns defaults to now eagle-console.tranquilitybase-demo.io
- [x ] Feature  
@sunderhill-gft
=> fixes dns change

tb-gcp-tr/shared-dac/jenkins-master.yaml
fixes change of jenkins image name and tag
=> jenkins image tag changed

tb-gcp-tr/gcr-configmap/main.tf, tb-gcp-tr/gcr-configmap/variables.tf, tb-gcp-tr/landingZone/no-itop/main.tf, tb-gcp-tr/shared-dac/jenkins-master.yaml
=> Issue 555 - Create Secret that contains the Root Folder ID

tb-gcp-tr/shared-dac/jenkins-master.yaml
update tb-jenkins version to 0.0.12 which contains GSR changes
=> update tb-jenkins version to 0.0.12

tb-gcp-tr/shared-dac/eagle_console.yaml
fixes issue 558
- [x ] Code style update (formatting, local variables)  
=> Update command on the gcpdacworker config file

tb-gcp-tr/shared-dac/eagle_console.yaml
closes #562 
- **@sunderhill-gft** please review.
=> #562 Updated `eagle_console.yaml`

tb-gcp-tr/shared-dac/jenkins-master.yaml
Latest jenkins image is now being used with this PR. 
=> Update version of tb-jenkins container in Eagle Kubernetes config

tb-gcp-tr/shared-dac/eagle_console.yaml
Closes #569
- @dangleft or @adamgft Please check the new features in a fresh new Landing Zone installation
=> #569 tb-gcp-tr\shared-dac\eagle_console.yaml

tb-gcp-tr/shared-dac/jenkins-master.yaml
=> Update Jenkins manifest file with latest version tags

tb-gcp-tr/shared-dac/jenkins-master.yaml
This reverts commit 22b4f2b8af531350e6042550fabf7a7e75242f9e.
=> Revert "Update jenkins-master.yaml (#606)"

tb-gcp-tr/landingZone/no-itop/variables.tf, tb-gcp-tr/shared-dac/jenkins-master.yaml
fixes issue-633
- **Review B** please review this part.  
closes #633
=> Fix error "Invalid Authentication details" when trying to deploy activators
